# Generated by Django 5.1.2 on 2024-10-31 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_date_created_user_date_joined_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
